version: '3.6'

services:
    nginx:
        build:
            args:
                VERSION: $NGINX_VERSION
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
           - php-fpm
        ports:
            - $NGINX_PORT:80

    php-fpm:
        build:
            args:
                VERSION: $PHP_VERSION
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/app
        command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'
