version: '3.6'

services:
    php-nginx:
        build:
            args:
                VERSION: $SERVER_NGINX_VERSION
                PHP_FPM_HOSTNAME: php-fpm
            context: ./server
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
           - php-fpm
        ports:
            - $SERVER_NGINX_PORT:80

    php-fpm:
        build:
            args:
                VERSION: $SERVER_PHP_VERSION
            context: ./server
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./server:/app
        command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'

    react:
        build:
            context: ./client
            dockerfile: ./docker/Dockerfile
            target: build
        volumes:
            - ./client:/usr/src/app
        ports:
            - $CLIENT_REACT_PORT:3000
