version: '3.6'

services:
    server-nginx:
        build:
            args:
                VERSION: $SERVER_NGINX_VERSION
                PHP_FPM_HOSTNAME: server-php-fpm
            context: ./server
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
           - server-php-fpm
        ports:
            - $SERVER_NGINX_PORT:80

    server-php-fpm:
        build:
            args:
                VERSION: $SERVER_PHP_VERSION
            context: ./server
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./server:/app
        command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'

    client-react:
        environment:
            - CLIENT_SERVER_BASE_URL=http://localhost:8050
        build:
            context: ./client
            dockerfile: ./docker/Dockerfile
            target: build
        volumes:
            - ./client:/usr/src/app
        ports:
            - $CLIENT_REACT_PORT:3000
