apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: hello-server
        image: harvestcloud/hello-server-php-fpm
        env:
        - name: CORS_ALLOW_ORIGIN
          value: "http://hello.harvestcloud.local"
      - name: nginx
        image: harvestcloud/hello-server-nginx
