name: Docker Build and Push

on:
  push:
    branches:
    - master

jobs:
  build_and_push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: server-nginx
      run: |
       NGINX_IMAGE_TAG="harvestcloud/hello-server-nginx:latest"
       docker build . --build-arg "VERSION=1.15" --build-arg "PHP_FPM_HOSTNAME=localhost" -f server/docker/nginx/Dockerfile --tag $NGINX_IMAGE_TAG
