name: Docker Build and Push

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        DOCKER_IMAGE_VERSION=latest
        DOCKER_IMAGE_TAG=${{ github.repository }}:$DOCKER_IMAGE_VERSION
        docker build . --build-arg "VERSION=7.3" -f docker/php-fpm/Dockerfile --tag $DOCKER_IMAGE_TAG
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push $DOCKER_IMAGE_TAG
